# conda environments:
#
LC-Rec                   /home/users/ntu/chen035/.conda/envs/LC-Rec
base                  *  /scratch/GPFS/app/apps/miniforge3/23.10

Looking in indexes: https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch==1.13.1+cu117 in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (1.13.1+cu117)
Requirement already satisfied: torchvision in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (0.14.1+cu117)
Requirement already satisfied: torchaudio in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (0.13.1+cu117)
Requirement already satisfied: typing-extensions in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from torch==1.13.1+cu117) (4.12.2)
Requirement already satisfied: numpy in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from torchvision) (1.24.1)
Requirement already satisfied: requests in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from torchvision) (2.32.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from torchvision) (10.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from requests->torchvision) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from requests->torchvision) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in ./.conda/envs/LC-Rec/lib/python3.8/site-packages (from requests->torchvision) (2022.12.7)
[2025-02-27 12:47:36,955] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-02-27 12:47:36,990] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/home/users/ntu/chen035/.conda/envs/LC-Rec/lib/python3.8/site-packages/torch/cuda/__init__.py", line 341, in get_device_name
    return get_device_properties(device).name
  File "/home/users/ntu/chen035/.conda/envs/LC-Rec/lib/python3.8/site-packages/torch/cuda/__init__.py", line 371, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/users/ntu/chen035/.conda/envs/LC-Rec/lib/python3.8/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
1.13.1+cu117
False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			Resource Usage on 2025-02-27 12:47:48.432407:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	JobId: 9556713.pbs101
	Project: personal-chen035
	Exit Status: 0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	NCPUs: Requested(16), Used(16)
	CPU Time Used: 00:00:05
	Memory: Requested(55gb), Used(365156kb)
	Vmem Used: 2453580kb
	Walltime: Requested(01:00:00), Used(00:00:39)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Execution Nodes Used: (x1001c0s4b0n1:ncpus=16:mem=57671680kb)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	No GPU-related information available for this job.
